baseURL = 'https://rschanz.org/'
languageCode = 'en-us'
title = 'Ryan Schanzenbacher'
theme = 'hugo-coder'

[markup.goldmark.renderer]
unsafe=true

[params]
author = "Ryan Schanzenbacher"
info = "Second Year Computing Security Student"
keywords = "blog,personal"
description = "Ryan Schanzenbacher's Personal website"
hideCredits = true
colorScheme = "dark"
hideColorSchemeToggle = true
avatarURL = "/imgs/profile/avatar.png"

[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/ryan77627/"
[[params.social]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/ryan-schanzenbacher"
  weight = 2
  icon = "fa fa-linkedin fa-2x"
[[params.social]]
  name = "Email"
  weight = 3
  url = "mailto:rjs1877@rit.edu"
  icon = "fa fa-envelope fa-2x"
[[params.social]]
  name = "Resume"
  weight = 4
  icon = "fa fa-file-text-o fa-2x"
  url = "/resume/Schanzenbacher_Ryan_Resume.pdf"
[[params.social]]
  name = "GPG Key"
  weight = 5
  icon = "fa fa-key-modern fa-2x"
  url = "gpgkey.asc"

#[[menu.main]]
#  name = "About"
#  weight = 1
#  url = "/about"

[[menu.main]]
  name = "Projects"
  weight = 2
  url = "/projects"
